basicform/basicapp/urls.py
from django.urls import path
from basicapp import views

app_name = 'basicapp'

urlpatterns=[
    path('otherone/', views.otherone, name='otherone'),
    path('othertwo/', views.othertwo,name='othertwo')
]

basicform/basicform/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index' ),
    path('users/', views.users,name='users' ),
    path('basicapp/', include('basicapp.urls'))
]

basicform/basicapp/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=254, unique=True)

basicform/basicapp/forms.py
from django import forms
from basicapp.models import User


class NewUserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = '__all__'

basicform/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import NewUserForm

# Create your views here.
def index(request):
    return render(request, 'basicapp/index.html')

def users(request):
    form = NewUserForm()

    if request.method =='POST':
        form = NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else :
            print('Error form invalid')

    return render(request, 'basicapp/users.html', {'form':form})


def otherone(request):
    dict ={'text':'Hello World', 'number': 100}
    return render (request,'basicapp/otherone.html',dict)

def othertwo(request):
    return render(request,'basicapp/othertwo.html')

basicform/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Internship Program</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'basicapp:otherone'%}">Other One</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'basicapp:othertwo'%}">Other Two</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
    </div>
    <div class="container">
      {% block body_block %}
<!-- Anything outside of this will be inherited if you use extend  -->
      {%endblock%}
    </div>


  </body>
</html>

basicform/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
<h1>Welcome!</h1>
<h2>Go to the /user to sign up!!</h2>
<a href="/users">SignUp</a>
{% endblock %}

basicform/templates/basicapp/otherone.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}

{%block body_block%}
<h1>This is Other one page</h1>
<h1>{{text | cut:'Hello'}}</h1>
<h1>{{number | add:"100"}}</h1>

{%endblock%}

basicform/templates/basicapp/othertwo.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}

{%block body_block%}
<h1>This is Other Two page</h1>
{%endblock%}

basicform/templates/basicapp/users.html
<!DOCTYPE html>
{% extends "basicapp/base.html" % }

{% block body_block %}
<h1>Please sing up here!</h1>
<form method="post">
  {{form.as_p}}
  {% csrf_token %}

  <input type="submit" value="Submit"  class="btn btn-primary">
</form>
{%endblock%}